### ISSUE TITLE
add jest tests

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#21]
see https://facebook.github.io/jest/

**Comment by choffmeister** [comment]
Is using jest a fixed decision? It does not play really nice with webpack. I have made much better experiences with using just karma with mocha as runner and unexpected-js (with unexpected-react) as assertion tool.

**Comment by tboerger** [comment]
Jest have been developed just for react testing :)

**Comment by tboerger** [comment]
> It works with any compile-to-JS language and integrates seamlessly with Babel.

**Comment by choffmeister** [comment]
Jest has nothing special to do with react. It is more a mocking framework than a specialised react testing framework. I was just asking, becase as soon as one wants to use any advanced stuff to goes beyond pure babel'ing (like css modules for example) then jest's lack of (proper) webpack integration leads to problems and hack arounds.

That is just my experience. That is why I was asking.

**Comment by bradrydzewski** [comment]
There are a number of benefits to JEST including its deep integration with React and the virtual DOM allowing us to run tests directly against the virtual DOM without phantomJS or a live browser. In my experience JEST works quite well.

At a more philosophical level, I'm opposed to a build tool (ie webpack) dictating the underlying technology stack we use in the project.

**Comment by bradrydzewski** [comment]
also is there a reason we need to use webpack to run our tests? If Jest has built-in support for babel could we just use `npm run test` where this executes the Jest command line utility? For some more background, I'm definitely looking for simplicity over sophistication for the project. It should be approachable for a novice front-end programmer, which is what I consider myself.

**Comment by tboerger** [comment]
I have not tried it but for me it looks like it just requires a simple preprocessor

**Comment by choffmeister** [comment]
The fact that there is no browser enviroment to provide for running tests is a big plus, true. And as long as one completely splits JS from the other stuff it works fine. Just thought that, since you for example require the styles directly in the component that needs them (which is a good thing from encapsulation point of view), you have to use workarounds to get it running. Simple preprocessor, yes. But in the end you will most likely duplicate the configuration for that. The example with the styles has solutions like mocking empty response or using `babel-plugin-webpack-loaders` (did not really work out for me), `babel-plugin-css-require-hook` (had quirks also). Another example is something like the `svg-react-loader` which lets you require SVGs and get them as ready to use react components (like for svg icons). 

In my philosophical view it is not really wrong to let the build tool also dictate how you run your tests. In other languages you would also not compile the production stuff with for example LLVM but run the tests with code compiled with GCC. Of coure you want your tests to test code in the same configuration as it will be bundled and deployed.

But np, we will get it to work with JEST. Just be prepared to

**Comment by choffmeister** [comment]
Maybe https://www.npmjs.com/package/jestpack can help... It looks very promising from the readme file

**Comment by alansouzati** [comment]
My two cents. I just love Jest I would recommend using the snapshot testing strategy.

https://facebook.github.io/jest/blog/2016/07/27/jest-14.html

Also an interesting blog post about the motivation of using Jest in our open source project:

https://blog.grommet.io/post/2016/09/01/how-we-landed-on-jest-snapshot-testing-for-javascript

**Comment by bradrydzewski** [comment]
I will be dedicating a good amount of time to this over the coming weeks. It took me a while to get it configured correctly, but I do have a jest test finally working:
https://github.com/drone/drone-ui/blob/master/src/shared/components/__tests__/status.test.js

I know writing tests isn't very exciting, but if anyone wants to help out let me know :)
