### ISSUE TITLE
pages: repository

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#210]
Implement repository page design (screenshot below)

- [x] implement initial page
- [x] implement hover effects
- [ ] implement tooltips
- [x] update icons and styles to match design
- [x] handle scenario where repository is inactive (show activate button)
- [ ] handle scenario where repository activation fails
- [x] handle scenario where repository is activated, but no builds exist yet

![repository-actions 2x](https://user-images.githubusercontent.com/817538/47926692-682faa80-de7e-11e8-856e-35e127d2caba.png)

**Comment by bradrydzewski** [comment]
cc @lnikell

**Comment by holdenrehg** [comment]
@bradrydzewski have you considered, in the new designs, adding a way to group repositories into branches? I implemented drone at my company and have been using it for a bit now, and often care the most about a few branches (master, stage, dev).

We do still trigger simple builds for feature branches that need to run, but then a failing feature branch build shows the entire repo as failing since it was the last build. Would be nice to somehow visualize the current status of Repo A -> master, vs Repo A -> staging, vs Repo A -> dev, etc.
