### ISSUE TITLE
components: activity feed

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#217]
Implement the activity feed.  I still need to add the endpoint, but it will probably be located at `GET /api/user/builds`

![in-progress 2x](https://user-images.githubusercontent.com/817538/47930302-c8c3e500-de88-11e8-9d18-407cf1bb7afa.png)

**Comment by pilt** [comment]
The activity feed of a repo has visual issues because of text being included as-is without truncating or similar. The screenshot belows shows how the body texts of Github PRs are rendered on 1.0.0-rc.1:

![image](https://user-images.githubusercontent.com/1878/48474111-23026580-e7fa-11e8-8924-bba921e729c0.png)

**Comment by proAlexandr** [comment]
Hi @pilt, thank you for an issue report. I fixed it here https://github.com/drone/drone-ui/commit/f5a7cc9c00a7d037a44c1664ebf1ef01f235118e.

**Comment by proAlexandr** [comment]
Hi, @bradrydzewski. I did a component for an activity feed. We (with @lnikell) think this feed should show last pending and running builds. Are we right?
Now, I can't find any API method to receive this builds. Can I add this method to API? Or you could handle it?

**Comment by bradrydzewski** [comment]
yes, we have `/api/user/builds/recent` which should only be invoked once on startup, and only if the user is authenticated.

**Comment by Indexyz** [comment]
![image](https://user-images.githubusercontent.com/7685264/49155109-1717b700-f355-11e8-9137-2090e47562bb.png)
When some active building, another success icon will rotate as building icon
> env: drone/drone:1.0.0-rc.1

**Comment by proAlexandr** [comment]
Hi, @Indexyz
Thank you for the bug report. I think I fixed it in https://github.com/drone/drone-ui/commit/4ba2c5d9b4f3f11d15d58d3b0eba0ed6104ea09a#diff-494e1bbeff2b0a4851e1229217191d2fR113

**Comment by proAlexandr** [comment]
@bradrydzewski 
>/api/user/builds/recent

I have a proposal to make this method better. Now it returns last 25 builds with any statuses, but BuildsFeed shows builds with pending and running statuses only. And if I have 29 successful and 30th pending/running build it won't be showed (because the limit is 25). So I think it makes sense to return all pending/runnings buils (without completed) which we have, with no limit.
