### ISSUE TITLE
Fix build card at the activity feed and build page

### ISSUE THREAD

**Issue by lnikell** [drone/drone-ui#219]
We have some mistakes within that component.
![image](https://user-images.githubusercontent.com/2697570/48505551-99798480-e847-11e8-96c5-a69cd021183b.png)

- ~Add author name instead of nickname. If author name does not exists use nickname~ (https://github.com/drone/drone-ui/issues/219#issuecomment-438794316)
- Remove hash of the commit
- date, duration, master should be moved to the left to give more space to branch name
- if branch name is truncated, by hover we should show a full name(just use html title attr should work)
![image](https://user-images.githubusercontent.com/2697570/48505648-d8a7d580-e847-11e8-81da-559e5d26dce5.png)

**Comment by bradrydzewski** [comment]
one minor comment -- we should use the username (e.g. github handle) instead of the full name. I received some feedback in our Slack channel when I first posted to the screenshot asking if we could display the username, which I agree makes more sense. In many cases, I know people by their github handle as opposed to their username :)  Also the availability of full name varies by provider (gilab vs github etc)

**Comment by lnikell** [comment]
@bradrydzewski I think it's more related to the open source when people don't know each other in person. Could we add it to the user settings and add option like in Slack setting that you could see usernames or names?

**Comment by lnikell** [comment]
![image](https://user-images.githubusercontent.com/2697570/48507903-781b9700-e84d-11e8-8940-b3bbc5c77ecd.png)

**Comment by bradrydzewski** [comment]
I really want to keep login name for now, and would prefer we avoid adding custom settings until we know enough users need such a capability. Lets revisit this once some of the more critical items are complete :)
