### ISSUE TITLE
unauthorized error for non-GET requests due to malformed csrf header

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#26]
changed from `X-CSRF_TOKEN` to `X-CSRF-TOKEN` but still need to re-build the `drone/drone` container to include the updated UI

**Comment by tboerger** [comment]
CSRF checks doesn't make sense at all for token based APIs, so we should just drop it. It makes only sense if the API is secured by a session.

**Comment by choffmeister** [comment]
For auth it would also be a good way to receive an refreshsble JWT after logging in to the frontend. This could be stored in the local storage. This way there is also no need anymore for the STATE_FROM_SERVER thing since the token could include all necessary infos for rendering (like username etc).

This would then need some transparent token refresh logic on the client side, but this is not too hard. Already build this a few times.

**Comment by choffmeister** [comment]
Ok there is already a JWT :smile: Then I guess when the login page works we could implement the local storage thingy

**Comment by bradrydzewski** [comment]
> CSRF checks doesn't make sense at all for token based APIs, so we should just drop it. It makes only sense if the API is secured by a session.

drone server uses cookies which is why CSRF if required. This is not something I'm open to changing at this time, as it works quite well as implemented.
