### ISSUE TITLE
When dealing with a systemic error, the build page doesn't have a link to the commit/pull request

### ISSUE THREAD

**Issue by krainboltgreene** [drone/drone-ui#262]
Lets say you have an untrusted repository and you push a commit that uses a host volume. You get this nice error about needing to be trusted, but the rest of the normal build ui doesn't exist. There's no way to go from that error to the pull request that introduced to that error.

**Comment by bradrydzewski** [comment]
I am not sure Drone would be able to reliably provide such a capability.  The URL to open a pull request varies by provider, and Drone supports GitHub, GitHub Enterprise, Bitbucket, Bitbucket Server, GitLab, Gogs and Gitea.  The self hosted option all can use a base URL which further complicates things.

I think it is an interesting idea though, but this can be tricky to implement when you consider support for the broader set of non-GitHub providers.  With that being said, I do think we are missing a link back to the repository in general, which would be helpful and is something we can do, because we capture this data.

**Comment by krainboltgreene** [comment]
FWIW drone already generates a correct link for `push` events on Github (P or E) via the View Source button. It doesn't do it for `pr` events though :(

**Comment by bradrydzewski** [comment]
the View Source button link comes from the webhook.  What you are suggesting would require Drone to derive the correct URL which is not a capability that it has today.  And doing so across all the providers may not be possible.  I am just documenting the technical challenges here.

**Comment by krainboltgreene** [comment]
Ahhhhhhhh that makes a lot of sense.

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone/issues/2843
